#Google Cloud Endpoints configuration file
swagger: "2.0"
info:
  title: "Store Locator"
  description: "Generate a Google maps directions URL to the nearest 
  store based on user's current ZIP code or coordinates"
  version: "1.0.0"
host: "yourapp.appspot.com"
consumes:
- "text/plain"
produces:
- "text/uri-list"
schemes:
  - "https"
securityDefinitions:
  auth0_jwk:
    authorizationUrl: ""
    flow: "implicit"
    type: "oauth2"
    x-google-issuer: "https://yourapp.auth0.com/"
    x-google-jwks_uri: "https://yourapp.auth0.com/.well-known/jwks.json"
    x-google-audiences: "https://locatorUser1"
security:
  - auth0_jwk: []
paths:
  /locator/zip:
    get:
      summary: "Find nearest store by ZIP code"
      operationId: "ZIP"
      description: "ZIP code"
      parameters:
        -
          name: zip
          in: query
          required: true
          type: string
      responses:
        200:
          description: "Google Maps URL with directions from input ZIP to nearest store"
          schema: 
            type: string
        404:
          description: "Error Message"
          schema:
            type: string
  /locator/coordinates:
    get:
      summary: "Find nearest store by coordinates (latitude, longitude)"
      operationId: "Coordinates"
      description: "Latitude, Longitude"
      parameters:
        -
          name: coordinates
          in: query
          required: true
          type: string
      responses:
        200:
          description: "Google Maps URL with directions from input coordinates to nearest store"
          schema: 
            type: string
        404:
          description: "Error Message"
          schema:
            type: string
  /locator/test:
    get:
      summary: "test path"
      operationId: test
      responses:
        200:
          description: OK

